### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by DannyBen** [adsteel/hash_dot#24]
Hi,

I am looking to using this nice gem, and would like to raise a couple of points:

### 1. Readme mistake?

It seems like the README is wrong about what happens when you use default values globally. This code: 

```ruby
# globally
Hash.use_dot_syntax = true
Hash.hash_dot_use_default = true
{}.a #=> 'default'
```

returns `nil`, and not `'default'`. I think it is an important distinction to make, since this would probably be the desired behavior by people who are using global default.

### 2. Syntax for instance defaults

Another thing I was wondering about, is the syntax required to make a default on a per instance basis.

Right now, the README states that this is how to do it:

```ruby
h = Hash.new('default').to_dot(use_default: true)
```

But wouldn't it be more idiomatic and intuitive to allow users to do this instead?

```ruby
h = { my: 'hash' }.to_dot default: nil
```

### 3. Refinements instead of monkey-patching

~And one last thought - since this is monkey patching Hash (and Symbol), which are very fundumental components of the language, and are heavily used (and patched) in Rails - wouldn't it be safer to use refinements?~

EDIT: I take back the refinements thought, it will probably make it safer but much less usable.

**Comment by adsteel** [comment]
Thanks for the questions!

1. I think maybe there's a chance to make the PR clearer here, you're right. "default" is meant to indicate whatever the default value has been set to. I see how that could be confusing though. Feel free to open a PR clarifying the example.

2. I think that's another valid way to do it. I prefer the current way because it only adds functionality onto the Hash class, rather than mixing in new ways to achieve existing functionality. 

Does that make sense? Any other questions?

**Comment by DannyBen** [comment]
Well, yeah, it makes sense, to an extent.

I have written quite a lot of Ruby code, and never used `Hash.new` - so to me this notation is foreign and unnatural. So, your point in 2 perhaps makes sense from the "state of the code" perspective, but - to me at least - not yet from the user perspective. I could be wrong, but this is my initial thought.

**Comment by adsteel** [comment]
Going to close this for now, but happy to re-open if there's a bug or feature we can talk about further.
